
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 927221
	#The name of the modpack
	modpackName = "Orbit Cycle"
	#The version of the modpack
	modpackVersion = "0.5.5"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

